# Generated by Django 5.0.3 on 2024-10-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomButtons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(verbose_name='Ключ')),
                ('text', models.CharField(blank=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Кнопка',
                'verbose_name_plural': 'Кнопки',
                'db_table': 'custom_buttons',
            },
        ),
        migrations.CreateModel(
            name='CustomTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(verbose_name='Ключ')),
                ('text', models.CharField(blank=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Текст',
                'verbose_name_plural': 'Текста в боте',
                'db_table': 'custom_texts',
            },
        ),
        migrations.CreateModel(
            name='Mailings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(verbose_name='Сообщение')),
                ('mailing_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('complete', models.BooleanField(default=False, verbose_name='Отправленно')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Рассылки',
                'verbose_name_plural': 'Рассылка',
                'db_table': 'mailings',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(verbose_name='Telegram id')),
                ('role', models.CharField(blank=True, null=True, verbose_name='Роль')),
                ('fio', models.CharField(blank=True, null=True, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, null=True, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, null=True, verbose_name='Почта')),
                ('tg_username', models.CharField(blank=True, null=True, verbose_name='TG username')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
            },
        ),
    ]
